[package]
name = "eternal_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true

[lints]
workspace = true

[features]
default = ["experimental"]
experimental = [
    "bevy/experimental_bevy_feathers",
]
